server:
  port: 80
eureka:
  client:
#    不向eureka注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7103.com:7103/eureka,http://eureka7102.com:7102/eureka,http://eureka7101.com:7101/eureka
feign:
  hystrix:
    enabled: true