server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7103.com:7103/eureka,http://eureka7102.com:7102/eureka,http://eureka7101.com:7101/eureka
  instance:
    instance-id: zuul9527
    prefer-ip-address: true
info:
  app:
    author: hq
    applicationName: springcloudZuul
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
#忽略该请求 不能使用这个请求   "*" 隐藏所有
  ignored-services: springcloud-provider-dept
# 设置公共的前缀
  prefix: /hq
