server:
  port: 7101
spring:
  application:
    name: eureka-server
#eureka
eureka:
  instance:
    hostname: eureka7101.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7101.com:7103,http://eureka7102.com:7102